server:
  shutdown: graceful
  compression:
    enabled: on
spring:
  application:
    name: task-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${DOCKER_CONFIG_SERVER_URL}